# -*- coding: utf-8 -*-
"""NLP stackoverflow using Naive Bayes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YFB-bz13bAJyzACmEcnQTTKXqgvDT2iI
"""

import pandas as pd
import pickle
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.externals import joblib

df = pd.read_csv('stackoverflow.csv', encoding='latin-1')
df.head()

df.tags.value_counts()

#Features and Labels
df['tags'] = df['tags'].map({'javascript':0, 'python':1,'iphone':2, 'java':3})
X = df['post']
y = df['tags']

df.head()

#EXtract Feature With CountVectorizer
cv = CountVectorizer()
X = cv.fit_transform(X) #Fit the Data

pickle.dump(cv, open('transform.pkl', 'wb'))

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 42)

#Naive Bayes Classifier
from sklearn.naive_bayes import MultinomialNB

clf = MultinomialNB()
clf.fit(X_train, y_train)
clf.score(X_test, y_test)
filename = 'nlp_model.pkl'
pickle.dump(clf, open(filename, 'wb'))

# #Alternative Usage of Saved Model
# joblib.dump(clf, 'NB_stackoverflow_model.pkl')
# NB_spam_model = open('NB_stackoverflow_model.pkl','rb')
# clf = joblib.load(NB_stackoverflow_model)

